
version: '2'
volumes:
    grafana_data_2: {}
services:
# -------------------------------------------------------------------------
# Grafana - Graphical Interface
# -------------------------------------------------------------------------
  grafana:
    image: grafana/grafana:4.1.2
    volumes:
      - /etc/localtime:/etc/localtime
      - grafana_data_2:/var/lib/grafana
      - ./config/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - prometheus
    ports:
      - "3000:3000"

# -------------------------------------------------------------------------
# Prometheus -
# -------------------------------------------------------------------------
  prometheus:
    image: prom/prometheus:v1.5.2
    volumes:
        - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./config/alert.rules:/etc/prometheus/alert.rules
        - /etc/localtime:/etc/localtime
    command:
        - '-config.file=/etc/prometheus/prometheus.yml'
        # - '-alertmanager.url=http://10.0.7.157:9999'
    ports:
        - '9090:9090'

  # alertmanager:
  #     image: prom/alertmanager:v0.5.1
  #     volumes:
  #       - ./alertmanager.yml:/alertmanager.yml
  #       - /etc/localtime:/etc/localtime
  #     command:
  #         - '-config.file=/alertmanager.yml'
# -------------------------------------------------------------------------
# influxdb
# -------------------------------------------------------------------------
  influxdb:
    image: influxdb:1.1.1-alpine
    volumes:
     - /etc/localtime:/etc/localtime
    environment:
     - "INFLUXDB_ADMIN_ENABLED=true"
    ports:
     - "8083:8083"
     - "8086:8086"

# -------------------------------------------------------------------------
# Telegraf - Prom
# -------------------------------------------------------------------------
  telegraf-prom:
    image: apstra/telegraf:1.2
    command: telegraf -debug
    env_file:
      - variables.env
    volumes:
      - ./config/telegraf-prom.toml:/etc/telegraf/telegraf.conf
      - /etc/localtime:/etc/localtime
    ports:
        - '6666:6666'
        - '9126:9126'

# -------------------------------------------------------------------------
# Telegraf - Influx
# -------------------------------------------------------------------------
  telegraf-influx:
    image: apstra/telegraf:1.2
    command: telegraf -debug
    env_file:
      - variables.env
    volumes:
      - ./config/telegraf-influx.toml:/etc/telegraf/telegraf.conf
      - /etc/localtime:/etc/localtime
    ports:
        - '4444:4444'
